import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Modal from './components/Modal'

export const metadata = {
  title: 'SchedAI',
  description: 'Generated by create-next-app and is an ai powered Scheduler',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className='bg-[#F5F6F8]'>
        {children}
        <Modal></Modal>
      </body>
    </html>
  )
}
